### ISSUE TITLE
Website and documentation is down

### ISSUE THREAD

**Issue by theronic** [hoophq/sequence#26]
Currently down:
- https://decimals.app/sequence
- https://docs.decimals.app/docs/sequence

**Comment by m0k1** [comment]
I have found docs at spotlight site ...  
DOCS: https://decimals.stoplight.io/docs/sequence  
SITE: https://web.archive.org/web/20220407184723/https://decimals.app/sequence

**Comment by lgrkvst** [comment]
Thanks!

**Comment by andriosrobert** [comment]
nice @m0k1, I've put the website back on and updated the docs to your link.

**Comment by lgrkvst** [comment]
IT'S ALIVE!! IT'S ALIVE!! =D
